### ISSUE TITLE
Contributing

### ISSUE THREAD

**Issue by bsinky** [nightblade9/haxesharp#1]
Are you open to contributions at this point?

I see that the repo is very active, which is awesome! But, it could also mean that it's young enough that you're not currently accepting contributions, which would also be understandable.

As someone who uses C# professional, but is very interested in Haxe for personal projects, this project is very interesting to me!

Please let me know your thoughts on contributions to this project currently, for those who might be interested in getting involved (like me).  Thank you.

**Comment by nightblade9** [comment]
Hi,

Sorry for the late reply -- I didn't see your issue opened until now.

I'm in the same boat as you (C# developer by profession and I use Haxe for my own projects).  Sure, you're more than welcome to contribute whatever you like.

Please take a look at the README (I recently changed my philosophical approach -- this is not "just" a copy of the C# API in Haxe).  

The best way to contribute is to start using the library, and add functionality as-needed; this is the same model that I used to get it to where it is today. I will be more than happy to code-review your PRs, and you can become an independent contributor down the road if you so choose (no PR necessary).

My only question is, how much Haxe experience do you have? (I've used it on and off since around 2012-2013).

**Comment by bsinky** [comment]
I'll keep an eye out for C# APIs I'd like to have in Haxe.  I don't have anything specific in mind at the moment.  Actually, that's not true, a recent project has me really wanting C#-style binary numeric literals in Haxe, like `0b1110` and so on.

I found Haxe around 2012/2013 as well, back in the Haxe 2 days.  Started experimenting with it, made a few small games.  Honestly, I didn't write any Haxe for a while, between around 2015-2016 I wasn't very active with Haxe.  Over the last few months I picked it back up again though, and have been trying to stay active with it, monitoring `haxe` questions on StackOverflow, reviving an old Haxe project of mine, etc., just to stay sharp with the language.

There's always more to learn about it, of course.  Haxe macros are something I am admittedly not well versed in.  So, I appreciate any code-review advice you are able to provide.

Thanks!

**Comment by nightblade9** [comment]
That sounds good. As long as you're actively working on a project and using `haxesharp` as an upstream dependency, we should end up building out "real" requirements instead of just writing out entire swatches of the .NET API. 

I'm not proficient in macros either. Google is your friend (I looked at at least three haxelibs for short-lambdas C# style; I'm pretty sure at least two used macros, but I don't understand any of them.)

Feel free to start contributing. I'm going to close this issue (since it's not really an issue). You can reach me by email whenever you want to discuss any aspects of this library in detail.

Also, I'm not sure how familiar you are with continuous integration and unit testing. For HaxeSharp, the requirement is to unit test absolutely everything (that's possible to unit test). Travis-CI runs the builds, so we get notified if they failed (eg. failed tests).  You should be able to easily run the unit tests from the command-line (I use VSCode's console).

Looking forward to seeing your contributions!

**Comment by nightblade9** [comment]
Hi,

I took a look at your profile, and I think it would be mutually beneficial if the first few PRs had a bit more direction and/or mentoring. Are you open to that?

Also, how did you find out about this project? I literally didn't advertise or talk about it anywhere, online or offline.

**Comment by bsinky** [comment]
Sure, that works for me.

As to how I found the project, it was one of the first results on GitHub after searching "haxe" and sorting by Recently Updated.
